Khan/react-render-server

src/main.js
src/secret.js
src/secret_test.js
src/server.js
src/server_test.js

Currently, the `secret.matches` function is synchronous, which causes the server to lockup while it reads the secret file from the file system before it continues execution. I've introduced a change to make the `secret.matches` function asynchronous and updated tests to match the async function.
This change also consolidates secret checking into a middleware function that can be reused in any new functions that need secret checking.
https://gist.github.com/Phanatic/9a9a6113413e39a7cd796d110a28470d
*Client*
``` bash
curl -XPOST http://localhost:8080/flush;echo
{"error":"Missing or invalid secret"}
```
*Server*
``` bash
error: FATAL ERROR (Error: ENOENT: no such file or directory, open '/Users/phaniraj/Documents/github/ka/react-render-server/secret'): You must create a file:
error: …
```

Asynchronous secret validation

---

src/create-render-context.js
src/render.js

Summary:
This makes sure that global variables like `REACT_SSR` are set before
any script files are loaded that might make decisions based on such
values.
Test Plan:
`npm test`
Run this version of the server against webapp to check it all still works

[WEB-994] Ensure globals set before scripts loaded

---

src/fetch_package.js

Most recently, we deployed this code to check things out, and I noticed that we were getting the end profile result repeated for file fetches. I tracked it down and have fixed it in this PR.
Also removed some imports that weren't used, fixed a spelling error in a comment, and deleted a comment that was no longer true.
Tested using latest webapp and verified the log doesn't have things listed twice.
Also ran `npm test`.

Fix issue where we are double logging profiling

---

.babelrc
.gitignore
.vscode/launch.json
app.js
deploy.sh
package-lock.json
package.json
src/arguments.js

This PR adds babel to react-render-server in preparation for supporting flow-types.
To ensure an almost seamless fit with webapp, this installs babel as a dependency and then runs in on install so that when we get the commit via webapp's package.json, it will build and provide the built code ready to run in node. The only webapp change required when updating to a version with this change is to modify the code that launches the server so that it references the built version of `main.js` instead of the `src` version.
We currently target node 8 since that's the version devs are running locally.
This also updates the `deploy.sh` to perform the build operation so that the dist files are created and modifies the `package.json` main to point to `dist/main.js` so that the app-engine-flex build …

Get things building with babel

---

flow-typed/custom/jsdom.js
src/configure-apollo-network.js
src/create-render-context.js
src/render.js
src/types.js

This builds on the previous PR by adding a new libdef for jsdom, lovingly crafted by hand from the typescript equivalent, with some updates to mirror the API we expect it to have based off documentation
Also adds a custom version of it that adds even more utilities that we specifically set, such as the apollo configuration

Add flow to configure-apollo-network.js

---

flow-typed/custom/apollo-cache-inmemory.js
flow-typed/custom/argparse.js
src/arguments.js
src/configure-apollo-network.js
src/render.js
src/render_apollo_test.js
src/render_test.js
src/server.js
src/types.js

This adds flow types to `render.js` as well as refactoring some code to tidy up how we do things.
Namely:
- Change `configureApolloClient` so that it doesn't need to know how it all gets used
- Add libdef for `argparse`
- Add libdef for `apollo-cache-inmemory`
- Add more strong types to things where we can and increase flow coverage
Before this change:
```shell
npx flow batch-coverage src
Coverage results from 11 file(s):
/Users/jeffyates/khan/react-render-server/src/types.js: 100.00% (18 of 18 expressions)
/Users/jeffyates/khan/react-render-server/src/server.js: 88.17% (395 of 448 expressions)
/Users/jeffyates/khan/react-render-server/src/secret_test.js: 77.01% (134 of 174 expressions)
/Users/jeffyates/khan/react-render-server/src/secret.js: 100.00% (93 of 93 expressions) …
```

Add flow types to render.js

---

.eslintrc
app.js
package.json
src/create-render-context.js
src/fetch_package_test.js
src/render.js
src/render_apollo_test.js
src/render_test.js
src/server.js
src/server_test.js

This adds flow types to the remaining test files and turns on `import/no-commonj` lint rule.
Also makes sure `app.js` is linted and other tweaks.

Add flow types to the rest of the files

---

package-lock.json
package.json
src/fetch_package.js

This update adds the `keepaliveagent` dependency, allowing us to configure our `superagent` fetches to reuse sockets. This should enable us to to get a better download rate from Fastly when we demand a large number of files at once.
1. Tested in dev webapp that files are still downloading from webpack as we would want
2. TBD Deploy commit to GAE and then use testing utilities to send requests and verify things work against fastly; compare similar requests against the existing implementation to see if we notice any improvements in file retrieval.

Use keepalive agent to maintain server connections

---

deploy.sh
package.json

AppEngine standard [complains about ulimit usage](https://console.cloud.google.com/logs/viewer?project=khan-academy&minLogLevel=0&expandAll=false&timestamp=2019-10-30T22%3A57%3A13.016000000Z&customFacets&limitCustomFacetWidth=true&dateRangeStart=2019-10-30T21%3A57%3A13.275Z&dateRangeEnd=2019-10-30T22%3A57%3A13.275Z&interval=PT1H&resource=gae_app%2Fmodule_id%2Freact-render%2Fversion_id%2F191025-1142-cd9a8b41f82f&logName=projects%2Fkhan-academy%2Flogs%2Fstdout&logName=projects%2Fkhan-academy%2Flogs%2Fstderr&logName=projects%2Fkhan-academy%2Flogs%2Fappengine.googleapis.com%252Frequest_log&scrollTimestamp=2019-10-30T22%3A41%3A00.671247000Z&advancedFilter=resource.type%3D%22gae_app%22%0Aresource.labels.version_id%3D%22191025-1142-cd9a8b41f82f%22%0Aresource.labels.module_id%3D%22react-render%22% …

Remove ulimit and cleaning from start command

---

package-lock.json
yarn.lock

This is the result of running `npm audit fix` and updating the `yarn.lock` to match.
Stacked on #34 to test out the `yarn.lock` update code.

Fix audit issues

---

src/create-render-context.js

So, we have had a naïve solution to loading images during SSR, just returning an empty string. But an empty file is not a valid image, and so this can cause the page being rendered to output errors.
In addition, JSDOM incorrectly expects `abort` to be a call of request promises, but our empty results didn't have this method.
This update adds an `abort` noop to our `EMPTY` result, and a minimum viable `data:` url image that we can return as our fake image result. We rely on JSDOM to decode this for us, but sadly, it does so into a `Promise` that does not have `abort` and so we have to add our own noop to that too.

Address image load failures

---

package.json
src/fetch_package.js

Hi there! I happened upon this repo's use of `superagent-cache-plugin` and noticed that you had to import `gutResponse` directly from the `utils` file for use in your `prune` callback. Having `gutResponse` available in that context makes sense, so I cut a new release of the plugin that exposes `gutResponse` to the `prune` callback so you don't have to import outside the public API.

Use superagent-cache-plugin's new gutResponse param

---

src/server.js
src/server_test.js

We are seeing these errors getting logged and yet the error information
we are trying to embed in the log metadata is not there. This makes
working out what really happened a lot harder.
So, here we instead try to get the error information into a the
log string itself so that we can see what's happening in our logs.
We don't have a great story right now for testing our failure modes.
However, we can test this by sending a bad request that requests URLs
that we know don't exist, or by sending a request that uses JS that we
know will blow up when executed.
To do the second part, we need to serve a file that is broken. We can
coerce a webapp to do this.

WEB-1754 #"Land Change" #comment Put error information directly in log

---

src/fetch_package.js
src/fetch_package_test.js
src/server_test.js

It's possible that some of the 404 errors we're seeing from Fastly may be transient. So let's retry them!
Issue: https://khanacademy.atlassian.net/browse/WEB-1757
Test plan:
I ran the test suite and it passed.

WEB-1757: Retry fetches on 404 errors

---

src/fetch_package_test.js

We were worried that it might be caching error responses, but that doesn't seem to be the case based on my testing. I ended up adding a bunch of tests anyway, might as well keep them!
Issue: https://khanacademy.atlassian.net/browse/WEB-1759
Test plan:
`npm test`

WEB-1759: Add tests verifying that superagent-cache-plugin works

---

.flowconfig
.vscode/settings.json
package.json
src/create-render-context.js
src/custom-resource-loader.js
src/custom-resource-loader_test.js
src/main.js
src/patch-promise.js

This makes it so that all our promises are patched to have an abort
call by modifying the Promise prototype. The aim is to make sure that
when JSDOM closes, there is an abort function for it to call, working
around its bug where it assumes all fetched promises are abortable this way.
This also takes the `CustomResourceLoader` code and gives it its own
file and tests. This helps validate a core piece of our architecture
as well as verify that our patching is working.

[WEB-1753] Add abort to Promise prototype

---

src/configure-apollo-network.js
src/render_apollo_test.js

This is a diagnostics change. I've added the URL of the request being made so that we can verify it's what we expect.

1. Add URL to errors for Apollo

---

flow-typed/custom/@google-cloud/logging-winston.js
flow-typed/npm/winston_v3.x.x.js
src/logging.js
src/main.js
src/server.js

This adds the contextual request logging middleware to the render server.
It does not change things to use the `req.log` call that it adds. That will have to come in a follow-up diff.
Issue: WEB-1769
We can test this locally with the dev server to verify we're still getting logging output and then we can deploy and try it against the `ab` tool with some real requests before putting in against prod. There should not be any issues.

Get logging using the google middleware

---

src/create-render-context.js
src/custom-resource-loader.js
src/custom-resource-loader_test.js
src/fetch_package.js
src/fetch_package_test.js
src/logging.js
src/main.js
src/profile.js
src/render.js
src/render_apollo_test.js
src/render_test.js
src/secret.js
src/secret_test.js
src/server.js
src/server_test.js

We middleware that currently is used to profile how long a request takes. This change updates that to also allow us to scope logging to that request. I then update various pieces of our code to use that scoped logger. This allows us to easily get the current logger scope without having to pass the request or its logger around everywhere.
Issue: WEB-1769
(still running actual tests, but wanted to get the diff up)
1. Update webapp to use this commit using the `yarn update:rrs` command with the commit SHA.
1. Visit the LOHP or other location that SSRs and check that things are logging as we would expect them to
1. [When in prod/znd] See in the stackdriver logging that not only are things logged but they are now grouped beneath the relevant request entry

Add ability to scope logging to middleware request logger

---

flow-typed/npm/winston_v3.x.x.js
src/logging.js
src/server.js

The issue is that the `makeMiddleware` function in the `logging-watson` Google package adds its own transport if the second parameter does not indicate that one already exists. This results in two transports and therefore duplicate messages.
My first fix removed our own transport so that the middleware one gets added and is the only transport. This worked mostly except for anything that was logged outside of the express code. In those circumstances we got orphaned log messages and errors about a lack of a transport.
So, the fix I landed on was using our own transport as before, but also telling the middleware about it so that it does not add another. This addresses both the duplicate messages and the need for a transport outside of the express usage.
Unrelated, but low risk; this also …

Fix duplicate messages and add info to render log

---

package-lock.json
package.json
src/server.js
yarn.lock

This diff addresses WEB-1795. It makes our error codes more consistent and recategorizes a RENDER FAIL to be a 400 BAD REQUEST, as it should be.
Specifically,
1. We validate URLs and return 400 BAD REQUEST for bad ones
2. RENDER FAILs are now a 500 error
This adds a new dependency on `whatwg-url`. This is already an indirect dependency in JSDOM. This way, we use the same validation mechanism to validate URLs as the mechanism that was originally throwing the error.
All tests pass.
1. Update webapp to use this commit
2. `make serve` and visit some pages to see that it does not throw when valid pages are given
Once we are deployed in production, see that errors like:
```
RENDER FAIL (https: ///?author=2): TypeError: Invalid URL: https:///?author=2
at createRenderContext …
```

[WEB-1795] Return meaningful error codes

---

flow-typed/npm/winston_v3.x.x.js
src/get-request-id.js
src/get-request-id_test.js
src/main.js
src/request-id-middleware.js

This PR addresses WEB-1769.
Here we add a middleware right after the Google middleware. This new middleware calculates the requestID from the headers, if it can, and then replaces the `req.log` logger with a child logger that adds the requestID to the log metadata.
This cannot be tested in dev. We can test in dev that the regular logging works. To do that:
1. Update webapp to this commit SHA of RRS
2. `make serve`
3. Visit LOHP and verify it renders and the RRS logging has output as we might expect
For pre-production testing:
1. Deploy this commit SHA of RRS (*DO NOT* make it default)
2. Use the SSR tooling to test the deployed RRS (see Confluence SSR docs)
3. View the stackdriver logs to see that the log messages have the requestID in their metadata
Example of this pre-production testing …

[WEB-1769] Add GAE requestID to logs

---

package-lock.json
package.json
src/custom-resource-loader.js
src/fetch_package.js
src/server.js
yarn.lock

This ups the cache expiration to 24 hours (as the files themselves shouldn't be changing) and then uses the new logic for clearing the cache of unused files every 15 minutes. I think we'll want to test this in practice to see if there's a duration that makes more sense but I think this is a good starting point.
Related PR: https://github.com/Khan/cache-service-cache-module/pull/1
Issue: https://khanacademy.atlassian.net/browse/WEB-1980
Test plan:
`yarn test` passed. I think the rest we'll want to test in production to see how it works!

WEB-1980: Clear unused files from fetch cache to reduce OOM errors

---

package.json
yarn.lock

This is to address an issue with fresh checkouts of webapp where react-apollo would complain about there being multiple versions of graphql.

Update graphql so that its version matches webapp

---

package-lock.json
package.json
src/main.js
src/server.js
yarn.lock

This adds `heapdump` as a peer dependency and the appropriate code to load it (duplicated from the equivalent feature in the render-gateway.
This also updates various things to address audit issues.

[WEB-2497] Add heapdump loading
